### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Sodki** [TheJumpCloud/jumpcloud-dashboard#14]
This project has no license, so no one can actually use it or make changes.

**Comment by kmoorehead-jc** [comment]
Hello!

Apologize for missing the license in our initial release. With our next patch, we'll make sure to add this in.

Apologies for any inconvenience caused.

Have a good day!

**Comment by kmoorehead-jc** [comment]
Hello,

We have now added the appropriate license to this repository. Marking this issue as closed.

Thank you and have a nice day!
