### ISSUE TITLE
How do I use it with Linux?

### ISSUE THREAD

**Issue by KylePeterDavies** [TheJumpCloud/jumpcloud-dashboard#38]
Dear JumpCloud, 

I have tried to deploy this with Docker, using Powershell >{6.20, 6.2.4}, , and Ubuntu {14.04, 16.04, 18.04}, as well as Centos 8, 7 and Alpine, using Microsofts Powershell Dockerfile, and I am greeted by multiple errors.

```Powershell
pwsh -ExecutionPolicy Unrestricted Install-JumpCloud-Powershell-Dashboard.ps1
```

```Powershell
Install-Module PSCoreUpdate -force -Scope CurrentUser

Update-PowerShellCore

Install-Module "JumpCloud.Dashboard"  -Force

Start-JCDashboard -JumpCloudApiKey SOME_KEY
```

18.04
```
 | Dashboard0 8003    True UniversalDashboard.Services.DashboardService
web_1  | Start-Process : This command cannot be run due to the error: No such file or directory.
web_1  | At /root/.local/share/powershell/Modules/JumpCloud.Dashboard/1.2.1/Public/Start-JCDashboard.ps1:263 char:9
web_1  | +         Start-Process -FilePath:('http://127.0.0.1:' + "$($DashboardS ...
web_1  | +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
web_1  | + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
web_1  | + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

This error seems to be persistent across builds.

**Comment by btstevens** [comment]
Hello KyleGwynDavies, 
The errors you posted are related to the auto-launch of the dashboard when it first starts up. The dashboard should be running/hosted, you could confirm this by running `Get-uddashboard` and seeing if it is up. You could also comment out line 269 in `start-jcdashboard.ps1` to stop the auto-launch behavior.

Perhaps you could explain your use case for running the dashboard inside a docker container, this would help us assess and work out how best to help fix the issue.

**Comment by KyleGwynDavies** [comment]
Hello, I will get back to you on on the former, However the use case is so that we can deploy a container for monitoring our JumpCloud to AWS.

**Comment by KyleGwynDavies** [comment]
Dear @btstevens, then why does JumpCloud claim this runs on Linux without any of these instructions? Also  PSCoreUpdate is only supported on OSX, and Windows? 
```bash
WARNING: This cmdlet supports Windows/macOS Only.
```
